<?php

namespace App\Policies;

/**
 * Stands in for an app policy at the conventional location (e.g. generated by Filament Shield).
 * It allows everything so defining it does not change the behaviour of other tests.
 */
class TranslationPolicy
{
    public function viewAny($user): bool
    {
        return true;
    }

    public function view($user, $translation): bool
    {
        return true;
    }

    public function create($user): bool
    {
        return true;
    }

    public function update($user, $translation): bool
    {
        return true;
    }

    public function delete($user, $translation): bool
    {
        return true;
    }

    public function deleteAny($user): bool
    {
        return true;
    }
}
